(function(){
 const KEY='dominance_account_v1';
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function get(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}}
 function normalizeWebsite(url){try{const u=new URL(/^https?:\/\//i.test(String(url||''))?url:'https://'+url);return (u.hostname.replace(/^www\./,'')+u.pathname.replace(/\/+$/,'')).toLowerCase()}catch(_){return String(url||'').trim().toLowerCase()}}
 function stableAccountKey(url){const s=normalizeWebsite(url);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return 'site_'+(h>>>0).toString(36)}
 async function set(v){const normalized={...v,id:stableAccountKey(v.website),account_key:stableAccountKey(v.website)};localStorage.setItem(KEY,JSON.stringify(normalized));try{const r=await fetch('/api/accounts/active',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalized)});if(r.ok){const d=await r.json();if(d.account){const merged={...normalized,server_id:d.account.id,id:d.account.account_key||normalized.id,account_key:d.account.account_key||normalized.id};localStorage.setItem(KEY,JSON.stringify(merged));return merged}}else{console.warn('Server account sync failed',r.status,await r.text())}}catch(e){console.warn('Server account sync failed',e)}return normalized}
 async function hydrate(){try{const r=await fetch('/api/accounts/active',{cache:'no-store'});if(!r.ok)return get();const d=await r.json();if(d.account){const s=d.account,v={id:s.account_key||stableAccountKey(s.website),account_key:s.account_key||stableAccountKey(s.website),server_id:s.id,company_name:s.company_name,website:s.website,industry_key:s.industry_key,industry_name:s.industry_name,created_at:s.created_at,analysis:s.analysis||{}};localStorage.setItem(KEY,JSON.stringify(v));return v}}catch(e){console.warn('Server account hydrate failed',e)}return get()}
 async function clear(){localStorage.removeItem(KEY);try{await fetch('/api/accounts/active/clear',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})}catch(e){console.warn('Server account clear failed',e)}}
 function nameFromUrl(url){try{const h=new URL(url).hostname.replace(/^www\./,'');return h.split('.')[0].replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}catch(_){return 'Company'}}
 function requireAccount(){const a=get();if(!a){hydrate().then(v=>{if(v)location.reload();else location.replace('/os.html?create=1')});return null}return a}
 function industryLabel(a){return a?.industry_name||a?.analysis?.industry_name||a?.industry_key||'Business'}
 function installTheme(){if(document.querySelector('link[data-dominance-theme]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/dominance-theme.css?v=3';link.dataset.dominanceTheme='1';document.head.appendChild(link)}
 function installBrand(){if(document.getElementById('domGlobalBrand'))return;const style=document.createElement('style');style.textContent='.dom-global-brand{display:flex!important;align-items:center!important;gap:10px!important;text-decoration:none!important;color:#e9c45a!important;min-width:max-content}.dom-crown-d{position:relative;width:42px;height:50px;display:grid;place-items:center;font-family:Georgia,serif;font-size:42px;font-weight:700;line-height:1;color:#e8bd48;text-shadow:0 0 12px #d9a82f33}.dom-crown-d:before{content:"♛";position:absolute;top:-8px;left:8px;font-size:22px;line-height:1;color:#f0c94e;transform:scaleX(1.12)}.dom-word{font-family:Georgia,serif;font-size:20px;font-weight:700;letter-spacing:.13em;color:#e7c05a}.dom-global-brand:hover .dom-crown-d,.dom-global-brand:hover .dom-word{filter:brightness(1.18)}@media(max-width:650px){.dom-word{font-size:15px}.dom-crown-d{width:34px;font-size:34px}}';document.head.appendChild(style);const brand=document.createElement('a');brand.id='domGlobalBrand';brand.className='dom-global-brand';brand.href='/os.html';brand.setAttribute('aria-label','DOMINANCE OS');brand.innerHTML='<span class="dom-crown-d">D</span><span class="dom-word">DOMINANCE</span>';const old=document.querySelector('header .brand')||document.querySelector('header > div:first-child');if(old){old.replaceWith(brand)}else if(!document.querySelector('aside.side')){brand.style.cssText+='position:fixed;top:8px;left:16px;z-index:10000';document.body.appendChild(brand)}}
 function routeActive(href){const p=location.pathname.toLowerCase();if(href==='/')return p==='/'||p==='/index.html';return p===href.toLowerCase()}
 async function logout(){try{await fetch('/api/auth/logout',{method:'POST'})}catch(_){}location.replace('/login.html')}
 function augmentExistingSidebar(side){if(side.dataset.domAugmented==='1')return;side.dataset.domAugmented='1';const adminLabel=[...side.querySelectorAll('.section')].find(x=>String(x.textContent).trim().toUpperCase()==='ADMIN');if(adminLabel){const links=[['/admin.html','⚙ Data Connections'],['/diagnostics.html','⌁ Diagnostics'],['/database.html','▦ Collected Data']];for(const [href,label] of links){if(side.querySelector(`a[href="${href}"],a[href="${href.slice(1)}"]`))continue;const a=document.createElement('a');a.className='nav adminNav'+(routeActive(href)?' active':'');a.href=href;a.textContent=label;adminLabel.parentNode.insertBefore(a,adminLabel.nextSibling);}}
 const user=document.createElement('div');user.className='dom-existing-side-user';user.innerHTML='<div class="dom-side-company">'+esc(get()?.company_name||'DOMINANCE')+'</div><div class="dom-side-email" id="domSideEmailExisting">Signed in</div><button class="dom-side-logout" id="domSideLogoutExisting">Sign Out</button>';side.appendChild(user);user.querySelector('button').onclick=logout;fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(d?.user?.email){const e=document.getElementById('domSideEmailExisting');if(e)e.textContent=d.user.email}}).catch(()=>{})}
 async function installSidebar(){if(document.getElementById('domAppSidebar'))return;const existing=document.querySelector('aside.side');if(existing){augmentExistingSidebar(existing);return}document.body.classList.add('dom-with-sidebar');const nav=[['/os.html','⌂','Executive OS'],['/','◉','Market Radar'],['/competitor.html','◎','Competitor Intelligence'],['/campaign.html','◆','Campaign Manager'],['/creative.html','✦','Creative Intelligence']];const admin=[['/admin.html','⚙','Data Connections'],['/diagnostics.html','⌁','Diagnostics'],['/database.html','▦','Collected Data']];const a=get();const el=document.createElement('aside');el.id='domAppSidebar';el.className='dom-app-sidebar';el.innerHTML='<a class="dom-side-brand" href="/os.html"><span class="dom-side-d">D</span><span class="dom-side-word">DOMINANCE</span></a><div class="dom-side-label">INTELLIGENCE</div>'+nav.map(x=>`<a class="dom-side-link ${routeActive(x[0])?'active':''}" href="${x[0]}"><span class="dom-side-icon">${x[1]}</span><span>${x[2]}</span></a>`).join('')+'<div class="dom-side-label">ADMIN</div>'+admin.map(x=>`<a class="dom-side-link admin ${routeActive(x[0])?'active':''}" href="${x[0]}"><span class="dom-side-icon">${x[1]}</span><span>${x[2]}</span></a>`).join('')+'<div class="dom-side-spacer"></div><div class="dom-side-user"><div class="dom-side-company">'+esc(a?.company_name||'DOMINANCE')+'</div><div class="dom-side-email" id="domSideEmail">Signed in</div><button class="dom-side-logout" id="domSideLogout">Sign Out</button></div>';document.body.appendChild(el);document.getElementById('domSideLogout').onclick=logout;try{const r=await fetch('/api/auth/me',{cache:'no-store'});if(r.ok){const d=await r.json();if(d.user?.email)document.getElementById('domSideEmail').textContent=d.user.email}}catch(_){}
 }
 function accountBanner(a){if(document.getElementById('domAccountBanner'))return;const d=document.createElement('div');d.id='domAccountBanner';d.style.cssText='position:fixed;right:14px;bottom:14px;z-index:9999;background:#0b1820;border:1px solid #5c4820;border-radius:10px;padding:9px 11px;color:#f4f7f9;font:11px Arial;box-shadow:0 8px 24px #0008';d.innerHTML='<b style="color:#f3ce62">'+esc(a.company_name)+'</b><div style="color:#8297a4;margin-top:3px">'+esc(industryLabel(a))+' · persistent DOMINANCE account</div>';document.body.appendChild(d)}
 function adaptCompetitor(){const a=requireAccount();if(!a)return;accountBanner(a);const sub=document.querySelector('.sub');if(sub)sub.textContent='COMPETITOR INTELLIGENCE · '+a.company_name.toUpperCase();const hero=document.querySelector('.hero h1');if(hero)hero.textContent=a.company_name+' Competitor Intelligence'}
 function adaptCampaign(){const a=requireAccount();if(!a)return;accountBanner(a);const sub=document.querySelector('.sub');if(sub)sub.textContent='CAMPAIGN MANAGEMENT · '+a.company_name.toUpperCase();const title=document.querySelector('.hero h1');if(title)title.textContent=a.company_name+' Campaign Portfolio'}
 function adaptRadar(){const a=requireAccount();if(!a)return;accountBanner(a)}
 function ready(){installTheme();installBrand();hydrate().then(()=>installSidebar()).catch(()=>installSidebar())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
 window.DOMINANCE_CTX={get,set,hydrate,clear,requireAccount,nameFromUrl,industryLabel,adaptCompetitor,adaptCampaign,adaptRadar,installBrand,installTheme,installSidebar,stableAccountKey,normalizeWebsite};
})();