(function(){
  const KEY='dominance_creative_graph_v2';
  function rows(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(v))return v}catch{}return []}
  function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
  function pct(a,b){return b?100*a/b:0}
  function money(n){return '$'+Math.round(Number(n||0)).toLocaleString()}
  function score(r){const q=pct(r.qualified,r.conversions),roas=r.spend?r.revenue/r.spend:0,cvr=pct(r.conversions,r.clicks);return Math.min(100,Math.round(roas*7+q*.55+cvr*1.5))}
  function aggregate(data,key){const m={};data.forEach(r=>{const k=r[key]||'Unknown';if(!m[k])m[k]={name:k,spend:0,impressions:0,clicks:0,conversions:0,qualified:0,revenue:0};Object.keys(m[k]).filter(x=>x!=='name').forEach(x=>m[k][x]+=Number(r[x]||0))});return Object.values(m).map(x=>({...x,score:score(x)})).sort((a,b)=>b.score-a.score)}
  function measuredRows(data){return(data||[]).filter(r=>Number(r.spend||0)>0||Number(r.impressions||0)>0||Number(r.clicks||0)>0||Number(r.conversions||0)>0||Number(r.qualified||0)>0||Number(r.revenue||0)>0)}
  function render(target,platform){const el=document.getElementById(target);if(!el)return;const allRows=rows(),data=measuredRows(platform?allRows.filter(x=>x.platform===platform):allRows);if(!data.length){el.innerHTML='<div style="border:1px solid #20333e;border-radius:9px;padding:18px;background:#09161e;color:#8fa2ae;font-size:10px;line-height:1.5"><b style="color:#eef7fb">Awaiting measured creative performance</b><br>DOMINANCE will populate this graph only after connected advertising and downstream outcome data produce actual impressions, spend, conversions, qualified outcomes or attributed revenue. Draft approvals are not counted as performance.</div>';return}const angles=aggregate(data,'angle'),visuals=aggregate(data,'visual'),ctas=aggregate(data,'cta'),platforms=aggregate(data,'platform');const best=arr=>arr[0]||{name:'Learning',score:0,qualified:0,revenue:0,spend:0},bA=best(angles),bV=best(visuals),bC=best(ctas),bP=best(platforms);el.innerHTML=`<div class="graphKpis"><div class="graphKpi"><span>BEST MESSAGE ANGLE</span><b>${bA.name}</b><small>${bA.score}/100 outcome score</small></div><div class="graphKpi"><span>BEST VISUAL TYPE</span><b>${bV.name}</b><small>${bV.qualified} qualified outcomes</small></div><div class="graphKpi"><span>BEST CTA</span><b>${bC.name}</b><small>${money(bC.revenue)} attributed revenue</small></div><div class="graphKpi"><span>BEST PLATFORM</span><b>${bP.name}</b><small>${bP.spend?((bP.revenue/bP.spend).toFixed(1)+'x ROAS'):'learning'}</small></div></div><div class="graphTable"><div class="graphHead"><span>CREATIVE VARIABLE</span><span>SPEND</span><span>QUALIFIED</span><span>REVENUE</span><span>SCORE</span></div>${angles.slice(0,5).map(x=>`<div class="graphRow"><span><b>${x.name}</b><small>message angle</small></span><span>${money(x.spend)}</span><span>${x.qualified}</span><span>${money(x.revenue)}</span><span class="graphScore">${x.score}</span></div>`).join('')}</div><div class="graphExplain"><b>Learning rule:</b> DOMINANCE weights qualified outcomes and attributed revenue above clicks. Only measured observations appear here.</div>`}
  function approve(v){const data=rows();data.push({platform:v.platform,angle:v.angle||'New variant',visual:v.visual||'Generated concept',cta:v.cta||'Learn More',spend:0,impressions:0,clicks:0,conversions:0,qualified:0,revenue:0,status:'approved'});save(data)}
  window.DOMINANCE_CREATIVE_GRAPH={rows,aggregate,score,render,approve};
})();
