(function(){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 let state=null,pollTimer=null;
 async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
 function textPreview(a){if(!a.text_content)return'';let d=null;try{d=JSON.parse(a.text_content)}catch{};const vars=d?.variants||[];if(vars.length)return vars.slice(0,3).map((v,i)=>{const title=Array.isArray(v.headlines)?v.headlines.slice(0,3).join(' · '):(v.headline||v.hook||v.caption||'Variant');const body=Array.isArray(v.descriptions)?v.descriptions.slice(0,2).join(' / '):(v.primary_text||v.intro_text||v.body_copy||v.description||'');return `<div style="border-top:${i?'1px solid #1d303a':'0'};padding:${i?'8px 0 0':'0'};margin-top:${i?'8px':'0'}"><b>${esc(title)}</b><div style="color:#9db1bd;margin-top:4px">${esc(body)}</div><div style="margin-top:5px;color:#5de0c2">CTA: ${esc(v.cta||'—')}</div>${v.rationale?`<div style="margin-top:5px;color:#c6ad5f">Why: ${esc(v.rationale)}</div>`:''}</div>`}).join('');return `<pre style="white-space:pre-wrap;font:10px/1.45 Arial;color:#9db1bd">${esc(a.text_content.slice(0,1400))}</pre>`}
 function assetCard(a){const media=a.mime_type?.startsWith('image/')&&a.content_url?`<img src="${a.content_url}" style="width:100%;max-height:240px;object-fit:cover;border-radius:8px;border:1px solid #263946">`:a.mime_type?.startsWith('video/')&&a.content_url?`<video src="${a.content_url}" controls style="width:100%;max-height:260px;border-radius:8px;border:1px solid #263946"></video>`:'';const status=String(a.status||'').toUpperCase().replaceAll('_',' '),ec=a.evidence_counts||{},sources=(a.evidence_sources||[]).join(', ')||'none';const evidence=`<div style="margin-top:8px;border:1px solid ${a.research_backed?'#24513f':'#5b3434'};background:${a.research_backed?'#0d211a':'#231616'};border-radius:7px;padding:7px;font-size:9px;color:#9db1bd"><b style="color:${a.research_backed?'#73e6a2':'#ff9c9c'}">${a.research_backed?'RESEARCH-BACKED':'RESEARCH REQUIRED'}</b> · sources ${esc(sources)}<br>Market ${Number(ec.market||0)} · Search ${Number(ec.search||0)} · Competitors ${Number(ec.competitors||0)} · Changes ${Number(ec.competitor_changes||0)} · Measured learning ${Number(ec.measured_learning||0)}<br>Platform contract: ${esc((a.platform_requirements||[]).join(' · ')||'not recorded')}</div>`;return `<div style="border:1px solid #263946;border-radius:10px;background:#09161e;padding:11px"><div style="display:flex;justify-content:space-between;gap:8px"><div><b>${esc(a.platform||'Platform')}</b><div style="font-size:9px;color:#78909d">${esc(a.asset_category)} · ${esc(a.asset_format||'')}</div></div><span style="font-size:8px;color:${a.status==='approved'?'#5de0c2':'#f3ce62'}">${esc(status)}</span></div>${evidence}${media?`<div style="margin-top:8px">${media}</div>`:''}${a.text_content?`<div style="margin-top:8px">${textPreview(a)}</div>`:''}<div style="margin-top:8px;font-size:9px;color:#8195a3">Market: ${esc(a.market||'not specified')} · Angle: ${esc(a.message_angle||'research-led')}</div><div style="display:flex;gap:6px;margin-top:9px">${a.status==='approved'?'<span style="color:#5de0c2;font-size:9px">READY IN CAMPAIGN MANAGER</span>':`<button data-approve="${a.id}" style="border:1px solid #5de0c2;background:#17352d;color:#dff9f0;border-radius:7px;padding:6px 8px;font-size:9px;font-weight:800;cursor:pointer">Approve + Send to Campaign Manager</button><button data-reject="${a.id}" style="border:1px solid #5b3434;background:#231616;color:#ffb2b2;border-radius:7px;padding:6px 8px;font-size:9px;cursor:pointer">Reject</button>`}</div></div>`}
 function ensure(){let el=document.getElementById('domCreativeLibrary');if(el)return el;el=document.createElement('section');el.id='domCreativeLibrary';el.className='card';el.style.marginTop='14px';const perf=document.getElementById('performance');perf?.parentNode?.insertBefore(el,perf);return el}
 function count(obj,key){return Number(obj?.[key]||0)}
 function pipelineStage(p){const q=p.request_status||{};if(!p.provider?.openai_configured&&count(q,'review'))return'WAITING FOR OPENAI CREDENTIAL';if(count(q,'generating'))return'GENERATING';if(count(q,'review'))return'BRIEFS READY FOR GENERATION';if(count(q,'queued')||count(q,'claimed'))return'BUILDING PRODUCTION BRIEFS';if(count(q,'approval'))return'AWAITING APPROVAL';if(count(q,'failed'))return'NEEDS ATTENTION';return'IDLE / READY'}
 function render(){
  const el=ensure();if(!state){el.innerHTML='<div class="eyebrow" style="margin:0">RESEARCH + READY-TO-LAUNCH CREATIVE CMS</div><div class="brief" style="margin-top:8px">Loading evidence-backed creative portfolio…</div>';return}
  const r=state.research||{},p=state.portfolio||{},assets=p.assets||[],workers=state.workers||[],pipe=state.pipeline||{},qs=pipe.request_status||{},errs=pipe.recent_errors||[],stage=pipelineStage(pipe);
  const active=count(qs,'queued')+count(qs,'claimed')+count(qs,'review')+count(qs,'generating');
  const noAssetsMessage=active?`Production is active: ${count(qs,'queued')} queued · ${count(qs,'review')} briefs ready · ${count(qs,'generating')} generating. This panel refreshes automatically.`:count(qs,'failed')?'Generation has failed for one or more requests. See Pipeline Diagnostics above for the exact provider error.':'No generated assets yet. Click Research + Generate Portfolio to start a complete research → brief → generation cycle.';
  el.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><div><div class="eyebrow" style="margin:0">RESEARCH + READY-TO-LAUNCH CREATIVE CMS</div><h2 style="font-size:18px;margin:5px 0">Creative Portfolio</h2><div class="brief">DOMINANCE researches search intent, Market Radar demand, competitor assets/changes and measured creative performance, then produces evidence-grounded copy, images, video and landing-page concepts.</div></div><button id="domRunCreativeResearch" class="btn primary">Research + Generate Portfolio</button></div>
  <div style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-top:10px"><div class="metric"><span>SEARCH INTENTS</span><b>${(r.keywords||[]).length}</b></div><div class="metric"><span>DEMAND EVENTS</span><b>${(r.market_events||[]).length}</b></div><div class="metric"><span>COMPETITOR ASSETS</span><b>${(r.competitor_assets||[]).length}</b></div><div class="metric"><span>COMPETITOR CHANGES</span><b>${(r.competitor_events||[]).length}</b></div><div class="metric"><span>MEASURED LEARNING</span><b>${(r.performance||[]).length}</b></div></div>
  <div style="border:1px solid #29414e;border-radius:9px;padding:10px;background:#09161e;margin-top:10px"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b style="font-size:10px">Production Pipeline</b><span style="font-size:9px;color:${count(qs,'failed')?'#ff9c9c':'#5de0c2'}">${esc(stage)}</span></div><div style="display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px;margin-top:8px"><div class="metric"><span>QUEUED</span><b>${count(qs,'queued')}</b></div><div class="metric"><span>BRIEFS</span><b>${count(qs,'review')}</b></div><div class="metric"><span>GENERATING</span><b>${count(qs,'generating')}</b></div><div class="metric"><span>APPROVAL</span><b>${count(qs,'approval')}</b></div><div class="metric"><span>APPROVED</span><b>${count(qs,'approved')}</b></div><div class="metric"><span>FAILED</span><b>${count(qs,'failed')}</b></div></div><div style="margin-top:8px;font-size:9px;color:#8195a3">OpenAI: <span style="color:${pipe.provider?.openai_configured?'#5de0c2':'#ff9c9c'}">${pipe.provider?.openai_configured?'configured':'NOT CONFIGURED'}</span> · Text: ${esc(pipe.provider?.text_model||'—')} · Image: ${esc(pipe.provider?.image_model||'—')} · Video: ${esc(pipe.provider?.video_model||'not configured')} · production cycle ${Number(pipe.production_interval_minutes||1)}m</div>${errs.length?`<div style="margin-top:8px;border-top:1px solid #2f2525;padding-top:7px;color:#ff9c9c;font-size:9px">${errs.map(e=>`<div><b>#${e.id} ${esc(e.asset_category||'creative')}</b> · ${esc(e.platform||'')} · ${esc(e.error||'')}</div>`).join('')}</div>`:''}</div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px"><div style="border:1px solid #20333e;border-radius:9px;padding:10px;background:#09161e"><b style="font-size:10px">Research reasoning inputs</b><div style="margin-top:6px;font-size:9px;color:#8195a3;line-height:1.5">${(r.keywords||[]).slice(0,6).map(x=>`<div>Search: <span style="color:#d9e8ed">${esc(x.phrase)}</span> · ${esc(x.dominant_intent||'unclassified')} · commerciality ${Math.round(Number(x.commerciality_score||0))}</div>`).join('')||'<div>No current search-intent evidence yet.</div>'}${(r.market_events||[]).slice(0,4).map(x=>`<div>Market: <span style="color:#d9e8ed">${esc(x.geography_name)}</span> · ${esc(x.event_type)} · score ${Math.round(Number(x.score||0))}</div>`).join('')}${(r.competitor_assets||[]).slice(0,4).map(x=>`<div>Competitor: <span style="color:#d9e8ed">${esc(x.competitor_name)}</span> · ${esc(x.platform)} · ${esc(x.message_angle||x.asset_type||'asset')}</div>`).join('')}</div></div><div style="border:1px solid #20333e;border-radius:9px;padding:10px;background:#09161e"><b style="font-size:10px">Worker status</b><div style="margin-top:6px;font-size:9px;color:#8195a3;line-height:1.5">${workers.map(w=>`<div>${esc(w.worker_key)} · <span style="color:${w.status==='completed'?'#5de0c2':w.status==='partial_error'||w.status==='error'?'#ff9c9c':'#f3ce62'}">${esc(w.status||'no_run')}</span></div>`).join('')||'<div>No creative worker runs recorded yet.</div>'}</div></div></div>
  <div class="eyebrow" style="margin:14px 0 8px">GENERATED PORTFOLIO · ${assets.length} ASSETS</div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px">${assets.length?assets.map(assetCard).join(''):`<div style="grid-column:1/-1;border:1px solid #20333e;border-radius:9px;padding:18px;color:#8195a3">${esc(noAssetsMessage)}</div>`}</div>`;
  document.getElementById('domRunCreativeResearch')?.addEventListener('click',runResearch);el.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>approve(b.dataset.approve)));el.querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',()=>reject(b.dataset.reject)));
 }
 async function load(){try{state=await api('/api/creative-intelligence/library');render()}catch(e){ensure().innerHTML='<div class="eyebrow" style="margin:0">CREATIVE PORTFOLIO</div><div style="color:#ff9c9c;margin-top:8px;font-size:10px">'+esc(e.message)+'</div>'}}
 async function runResearch(){const b=document.getElementById('domRunCreativeResearch');if(b){b.disabled=true;b.textContent='Starting production…'}try{await api('/api/creative-intelligence/research',{method:'POST',body:'{}'});await load();if(pollTimer)clearInterval(pollTimer);let ticks=0;pollTimer=setInterval(async()=>{ticks++;await load();if(ticks>=12||state?.portfolio?.assets?.length){clearInterval(pollTimer);pollTimer=null}},5000)}catch(e){alert(e.message)}finally{if(b){b.disabled=false;b.textContent='Research + Generate Portfolio'}}}
 async function approve(id){try{const d=await api('/api/creative-intelligence/assets/'+id+'/approve',{method:'POST',body:'{}'});alert(`Approved. ${d.creative_ids?.length||0} creative item(s) are now ready in Campaign Manager.`);await load()}catch(e){alert(e.message)}}
 async function reject(id){try{await api('/api/creative-intelligence/assets/'+id+'/reject',{method:'POST',body:'{}'});await load()}catch(e){alert(e.message)}}
 function start(){window.regenerate=runResearch;render();load();setInterval(load,15000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
